[profile.default]
src = 'contracts'
out = 'out'
test = 'tests'
libs = ["lib"]

remappings = [
  '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
  'forge-std=lib/forge-std/src',
  'ds-test=lib/forge-std/lib/ds-test/src'
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config